environment: demo
released_at: 2026-08-13T23:44:40Z

api:
  repository: Eguzjimenez/e-commerce-api
  ref: 466fc5ba4757f4011892721398b978438a8c3182
  project: Concre_Innova_API/Concre_Innova_API.csproj

frontend:
  repository: Eguzjimenez/e-commerce
  ref: ad24d2d83f714e7f3bff2fd68a9bcf58996ea896
  directory: concre_innova_website

database:
  name: free-sql-db-6728341
  server: hogrider.database.windows.net
  ownership: external
  initial_deployment: full-script-or-bacpac
  migration_source: Concre_Innova_API/Database/Scripts
