environment: demo
released_at: 2026-08-22T04:36:01-06:00

api:
  repository: Eguzjimenez/e-commerce-api
  ref: e1fdf9c9a7168ca995fc103d19df1474145c26b8
  project: Concre_Innova_API/Concre_Innova_API.csproj

frontend:
  repository: Eguzjimenez/e-commerce
  ref: 5a178252b0f88651b4baa254a2e5ad99a1391c1c
  directory: concre_innova_website

database:
  name: free-sql-db-6728341
  server: hogrider.database.windows.net
  ownership: external
  initial_deployment: full-script-or-bacpac
  migration_source: Concre_Innova_API/Database/Scripts
